[env:esp32-c6-devkitc-1]
platform = espressif32
board = esp32-c6-devkitc-1
framework = espidf
monitor_speed = 115200

lib_deps = 
    https://github.com/micro-ROS/micro_ros_platformio

build_flags = 
        -D PROJECT_VER=\"1.0.0\"