[env:esp32-c6-devkitc-1]
platform = espressif32
board = esp32-c6-devkitc-1
framework = espidf
monitor_speed = 115200
board_build.flash_size = 4MB
build_flags =
        -I ../libs/micro-ros-espidf/include
        -I ../libs/micro-ros-espidf/rcl/include