idf_component_register(
    SRCS 
        "src/rcl_impl.c"
        "src/rclc_impl.c"
        "src/rcutils_impl.c"
        "src/rosidl_impl.c"
    INCLUDE_DIRS 
        "."
        "action_msgs"
        "actionlib_msgs"
        "builtin_interfaces"
        "common_interfaces"
        "composition_interfaces"
        "diagnostic_msgs"
        "example_interfaces"
        "geometry_msgs"
        "include"
        "libyaml_vendor"
        "lifecycle_msgs"
        "micro_ros_msgs"
        "micro_ros_utilities"
        "microcdr"
        "microxrcedds_client"
        "nav_msgs"
        "rcl"
        "rcl_action"
        "rcl_interfaces"
        "rcl_lifecycle"
        "rcl_logging_interface"
        "rcl_logging_noop"
        "rclc"
        "rclc_lifecycle"
        "rclc_parameter"
        "rcutils"
        "rmw"
        "rmw_implementation"
        "rmw_implementation_cmake"
        "rmw_microros"
        "rmw_microxrcedds"
        "rmw_microxrcedds_c"
        "ros2trace"
        "rosgraph_msgs"
        "rosidl_adapter"
        "rosidl_cli"
        "rosidl_cmake"
        "rosidl_default_generators"
        "rosidl_default_runtime"
        "rosidl_generator_c"
        "rosidl_generator_cpp"
        "rosidl_generator_dds_idl"
        "rosidl_parser"
        "rosidl_runtime_c"
        "rosidl_runtime_cpp"
        "rosidl_typesupport_c"
        "rosidl_typesupport_cpp"
        "rosidl_typesupport_interface"
        "rosidl_typesupport_introspection_c"
        "rosidl_typesupport_introspection_tests"
        "rosidl_typesupport_microxrcedds_c"
        "rosidl_typesupport_microxrcedds_c_tests"
        "rosidl_typesupport_microxrcedds_cpp"
        "rosidl_typesupport_microxrcedds_cpp_tests"
        "rosidl_typesupport_microxrcedds_test_msg"
        "sensor_msgs"
        "sensor_msgs_py"
        "shape_msgs"
        "src"
        "statistics_msgs"
        "std_msgs"
        "std_srvs"
        "stereo_msgs"
        "test_interface_files"
        "test_msgs"
        "test_rmw_implementation"
        "test_tracetools"
        "test_tracetools_launch"
        "tracetools"
        "tracetools_launch"
        "tracetools_read"
        "tracetools_test"
        "tracetools_trace"
        "trajectory_msgs"
        "ucdr"
        "unique_identifier_msgs"
        "uxr"
        "visualization_msgs"
    REQUIRES esp_system freertos log
)
